# Generated by Django 3.1.1 on 2020-09-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_passwords_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwords',
            name='user_password',
        ),
        migrations.AlterField(
            model_name='passwords',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='websitename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='websiteurl',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
