# Generated by Django 3.1.1 on 2020-09-29 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20200929_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='websitename',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='websiteurl',
            field=models.CharField(max_length=200),
        ),
    ]
